import UIKit
import PDFKit

struct PDFReportGenerator {
    let stats: GlucoseStats
    let days: Int

    func generate() -> Data {
        let filtered = stats.filtered(days: days)
        let pageRect = CGRect(x: 0, y: 0, width: 612, height: 792) // US Letter
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)

        return renderer.pdfData { ctx in
            ctx.beginPage()
            let c = ctx.cgContext

            var y: CGFloat = 48

            // ── Header ──
            y = drawText("InsulinCalculator — Diabetes Report", at: CGPoint(x: 40, y: y),
                         font: .boldSystemFont(ofSize: 22), color: .systemBlue, width: 532)
            y += 6
            let dateRange = "\(formattedDate(Calendar.current.date(byAdding: .day, value: -days, to: Date())!)) – \(formattedDate(Date()))"
            y = drawText(dateRange, at: CGPoint(x: 40, y: y),
                         font: .systemFont(ofSize: 12), color: .secondaryLabel, width: 532)
            y += 4
            y = drawText("Generated \(formattedDate(Date()))", at: CGPoint(x: 40, y: y),
                         font: .systemFont(ofSize: 11), color: .tertiaryLabel, width: 532)
            y += 16

            // Divider
            c.setStrokeColor(UIColor.separator.cgColor)
            c.setLineWidth(0.5)
            c.move(to: CGPoint(x: 40, y: y)); c.addLine(to: CGPoint(x: 572, y: y)); c.strokePath()
            y += 20

            // ── Summary stats row ──
            y = drawSectionHeader("Summary (\(days)-Day Period)", y: y)
            y += 10
            let cols: [(String, String, UIColor)] = [
                ("Est. A1C", String(format: "%.1f%%", filtered.estimatedA1C), .systemBlue),
                ("Avg BG", String(format: "%.0f %@", filtered.averageBG, stats.unit.rawValue), .systemPurple),
                ("Avg Dose", String(format: "%.1f u", filtered.averageDose), .systemIndigo),
                ("Readings", "\(filtered.count)", .systemTeal),
            ]
            let colW: CGFloat = 532 / 4
            for (i, col) in cols.enumerated() {
                let x = 40 + CGFloat(i) * colW
                drawStatBox(title: col.0, value: col.1, color: col.2, rect: CGRect(x: x, y: y, width: colW - 8, height: 60), ctx: c)
            }
            y += 72

            // ── TIR ──
            y = drawSectionHeader("Time in Range", y: y)
            y += 10
            let tirRows: [(String, Double, UIColor)] = [
                ("In range (\(stats.unit == .mgdL ? "70–180 mg/dL" : "3.9–10.0 mmol/L"))", filtered.timeInRange, .systemGreen),
                ("Above range", filtered.timeAboveRange, .systemOrange),
                ("Below range", filtered.timeBelowRange, .systemRed),
            ]
            for row in tirRows {
                y = drawTIRRow(label: row.0, pct: row.1, color: row.2, y: y)
                y += 6
            }
            y += 10

            // ── Dose history table ──
            if y > 580 { ctx.beginPage(); y = 48 }
            y = drawSectionHeader("Dose History (most recent \(min(filtered.count, 30)))", y: y)
            y += 10

            // Table header
            let cols2 = ["Date & Time", "BG", "Carbs", "Dose", "Notes"]
            let widths: [CGFloat] = [160, 80, 70, 70, 152]
            y = drawTableRow(cells: cols2, widths: widths, y: y, isHeader: true, ctx: c)

            let df = DateFormatter()
            df.dateStyle = .short; df.timeStyle = .short
            for entry in filtered.entries.prefix(30) {
                if y > 730 { ctx.beginPage(); y = 48; y = drawTableRow(cells: cols2, widths: widths, y: y, isHeader: true, ctx: c) }
                let cells = [
                    df.string(from: entry.date),
                    String(format: "%.0f %@", entry.currentBG, entry.glucoseUnit.rawValue),
                    entry.carbs > 0 ? String(format: "%.0fg", entry.carbs) : "—",
                    String(format: "%.1f u", entry.totalDose),
                    entry.notes.isEmpty ? "—" : entry.notes
                ]
                y = drawTableRow(cells: cells, widths: widths, y: y, isHeader: false, ctx: c)
            }

            y += 20
            // ── Footer ──
            drawText("This report is generated by InsulinCalculator and is for informational purposes only. It does not replace professional medical advice.",
                     at: CGPoint(x: 40, y: y), font: .italicSystemFont(ofSize: 9), color: .tertiaryLabel, width: 532)
        }
    }

    // MARK: - Drawing helpers

    @discardableResult
    private func drawText(_ text: String, at point: CGPoint, font: UIFont, color: UIColor, width: CGFloat) -> CGFloat {
        let attrs: [NSAttributedString.Key: Any] = [.font: font, .foregroundColor: color]
        let str = NSAttributedString(string: text, attributes: attrs)
        let rect = CGRect(x: point.x, y: point.y, width: width, height: 200)
        str.draw(in: rect)
        let height = str.boundingRect(with: CGSize(width: width, height: .greatestFiniteMagnitude),
                                       options: .usesLineFragmentOrigin, context: nil).height
        return point.y + height
    }

    @discardableResult
    private func drawSectionHeader(_ text: String, y: CGFloat) -> CGFloat {
        drawText(text, at: CGPoint(x: 40, y: y),
                 font: .boldSystemFont(ofSize: 14), color: .label, width: 532)
    }

    private func drawStatBox(title: String, value: String, color: UIColor, rect: CGRect, ctx: CGContext) {
        ctx.setFillColor(color.withAlphaComponent(0.08).cgColor)
        ctx.fill(rect.insetBy(dx: 0, dy: 0))
        let titleAttrs: [NSAttributedString.Key: Any] = [.font: UIFont.systemFont(ofSize: 10), .foregroundColor: UIColor.secondaryLabel]
        NSAttributedString(string: title, attributes: titleAttrs).draw(at: CGPoint(x: rect.minX + 6, y: rect.minY + 6))
        let valAttrs: [NSAttributedString.Key: Any] = [.font: UIFont.boldSystemFont(ofSize: 20), .foregroundColor: color]
        NSAttributedString(string: value, attributes: valAttrs).draw(at: CGPoint(x: rect.minX + 6, y: rect.minY + 22))
    }

    @discardableResult
    private func drawTIRRow(label: String, pct: Double, color: UIColor, y: CGFloat) -> CGFloat {
        // Bar background
        let barX: CGFloat = 40, barW: CGFloat = 532, barH: CGFloat = 20
        // Background
        let bgPath = UIBezierPath(roundedRect: CGRect(x: barX, y: y, width: barW, height: barH), cornerRadius: 4)
        UIColor.systemGray5.setFill(); bgPath.fill()
        // Fill
        let fillW = max(0, min(barW * CGFloat(pct), barW))
        if fillW > 0 {
            let fillPath = UIBezierPath(roundedRect: CGRect(x: barX, y: y, width: fillW, height: barH), cornerRadius: 4)
            color.withAlphaComponent(0.7).setFill(); fillPath.fill()
        }
        // Label
        let labelAttrs: [NSAttributedString.Key: Any] = [.font: UIFont.systemFont(ofSize: 10), .foregroundColor: UIColor.label]
        NSAttributedString(string: label, attributes: labelAttrs).draw(at: CGPoint(x: barX + 6, y: y + 4))
        // Pct
        let pctStr = String(format: "%.0f%%", pct * 100)
        let pctAttrs: [NSAttributedString.Key: Any] = [.font: UIFont.boldSystemFont(ofSize: 10), .foregroundColor: color]
        let pctW = NSAttributedString(string: pctStr, attributes: pctAttrs).size().width
        NSAttributedString(string: pctStr, attributes: pctAttrs).draw(at: CGPoint(x: barX + barW - pctW - 6, y: y + 4))
        return y + barH
    }

    @discardableResult
    private func drawTableRow(cells: [String], widths: [CGFloat], y: CGFloat, isHeader: Bool, ctx: CGContext) -> CGFloat {
        let rowH: CGFloat = 22
        if isHeader {
            ctx.setFillColor(UIColor.systemGray5.cgColor)
            ctx.fill(CGRect(x: 40, y: y, width: 532, height: rowH))
        }
        var x: CGFloat = 40
        for (i, cell) in cells.enumerated() {
            let font: UIFont = isHeader ? .boldSystemFont(ofSize: 10) : .systemFont(ofSize: 10)
            let color: UIColor = isHeader ? .label : (i == 3 ? .systemBlue : .label)
            let attrs: [NSAttributedString.Key: Any] = [.font: font, .foregroundColor: color]
            NSAttributedString(string: cell, attributes: attrs).draw(at: CGPoint(x: x + 4, y: y + 5))
            x += widths[i]
        }
        // Bottom border
        ctx.setStrokeColor(UIColor.separator.cgColor)
        ctx.setLineWidth(0.3)
        ctx.move(to: CGPoint(x: 40, y: y + rowH))
        ctx.addLine(to: CGPoint(x: 572, y: y + rowH))
        ctx.strokePath()
        return y + rowH
    }

    private func formattedDate(_ date: Date) -> String {
        let f = DateFormatter(); f.dateStyle = .medium; f.timeStyle = .none
        return f.string(from: date)
    }
}
